version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub
      - docker login --username $DOCKER_USER --password $DOCKER_PASSWORD
  build:
    commands:     
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
  post_build:
    commands:
      - docker push $IMAGE_REPO_NAME:$IMAGE_TAG
